# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsZz9FXnnZGajlMchLfvvq5RpvudR2gz
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, chi2

df = pd.read_csv("/content/Titanic_train.csv")

num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include="object").columns

df[num_cols] = SimpleImputer(strategy="mean").fit_transform(df[num_cols])
df[cat_cols] = SimpleImputer(strategy="most_frequent").fit_transform(df[cat_cols])

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)

y = df["Survived"]
X = df.drop(["Survived", "Name", "Ticket", "Cabin"], axis=1, errors="ignore")

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

selector = SelectKBest(score_func=chi2, k=5)
X_selected = selector.fit_transform(abs(X_scaled), y)

selected_features = X.columns[selector.get_support()]

result = pd.DataFrame(X_selected, columns=selected_features)
result.to_csv("selected_features.csv", index=False)

print(selected_features)

import os
os.listdir("/content")

from google.colab import files
files.download("/content/selected_features.csv")